name: Integration Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 5" # Every Friday at 13:00 UTC
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up proxy
      env:
        SSH_HOST: ${{ secrets.SSH_HOST}}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        PROXY_IP: ${{ secrets.PROXY_IP }}
        PROXY_PORT: ${{ secrets.PROXY_PORT }}
      run: |
        mkdir ~/.ssh
        ssh-keyscan -H -p ${SSH_PORT} ${SSH_HOST} >> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "${SSH_KEY}"
        ssh -fN -L "${PROXY_PORT}:${PROXY_IP}:${PROXY_PORT}" "${SSH_USER}@${SSH_HOST}" -p ${SSH_PORT}
    - uses: actions/checkout@v3
    - name: Run tests
      env:
        # Some providers - e.g. Luci - require that the request originates from
        # the United Kingdom, however GitHub's servers are in the United States.
        # Running the requests via a proxy based in the UK circumnavigates this.
        LUCI_PROXY: ${{ secrets.PROXY_URL }}
        NODE_TLS_REJECT_UNAUTHORIZED: '0'
      run: |
        npm install
        npm run integration-ci
