changelog:
    exclude:
      labels:
        - ignore-for-release
      authors:
        - Libraree
    categories:
      - title: Major Changes
        labels:
          - Semver-Major
          - breaking-change
      - title: New Features
        labels:
          - Semver-Minor
          - enhancement
      - title: Other Changes
        labels:
          - "*"